### PR TITLE
Enable the client to send multiple events right after each other

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by assertchris** [comment]
Currently:

``` php
$client->emit("handle", "param1", "param2");
$server->emitter()->emit("handle", "param1", "param2");
```

remaining data: `""`

With your code:

``` php
$client->emit([["handle1", "param1", "param2"],["handle2", "param1", "param2"]]);

$server->emitter()->emit("handle1", "param1", "param2");
```

remaining data: `"],["handle2", "param1", "param2"]]"`

Unless I'm missing something... :/

**Comment by assertchris** [comment]
Just to be clear: I really like the idea of batching events, but I think the patch needs work.

**Comment by hannesvdvreken** [comment]
Ha no :-) I meant firing multiple events from the client right after one another.

``` php
$client->emit("handle", "param1", "param2");
$client->emit("otherhandle", "param1");
```

This would call `handleData` in the server with 2 serialized array strings concatenated. Unserialize only returns the first array. Give it a run and keep an eye on the value of $data.

If it's not clear then that's my fault.

**Comment by assertchris** [comment]
Right, I missed that!

**Pull request merged**
