### PR TITLE
Allow events to fired after a delay

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by assertchris** [comment]
The Client has the event loop, so it can delay events from there. Not sure this is needed...

**Comment by hannesvdvreken** [comment]
Just playing around ;-)

The idea I had was that the client process could move on with it's task or even shut down completely and don't need to remember tasks etc.

**Comment by assertchris** [comment]
I don't want to merge this right now, but I want to leave it open to remind me to think about it again, later.

**Comment by hannesvdvreken** [comment]
Your call. I'm cool with that. I just played with it and wanted to show you this. What you want to do with this is up to you.

**Pull request closed without merging**
